name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  validate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Verify all checks passed
        run: |
          # Query GitHub API to ensure all checks passed for this commit
          gh api repos/${{ github.repository }}/commits/${{ github.sha }}/status \
            --jq '.state' | grep -q "success" || {
            echo "❌ CI checks have not passed for this commit"
            echo "Please ensure all CI checks pass before creating a release tag"
            exit 1
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: validate-tests
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.6.2
        with:
          myToken: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
