name: Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'CHANGELOG.md'

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Create Release Pull Request or Publish
      id: changesets
      uses: changesets/action@v1
      with:
        title: 'Release: Version Packages'
        commit: 'release: version packages'
        publish: npm run publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}